import type { Evidence, User } from './types'

export const REQUIRED_HOURS = 20

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    fullName: 'Aisha Patel',
    studentId: 'S001234',
    email: 'aisha.patel@uni.edu',
    degree: 'Bachelor of Engineering (Electrical)',
    yearOfStudy: 2,
    role: 'student',
    bio: 'Passionate about renewable energy and robotics.',
    phone: '+61 412 345 678',
  },
  {
    id: 'u2',
    fullName: 'Admin User',
    studentId: 'A000001',
    email: 'admin@wiesoc.edu',
    degree: 'Bachelor of Engineering (Software)',
    yearOfStudy: 4,
    role: 'admin',
  },
]

export const MOCK_EVIDENCE: Evidence[] = [
  {
    id: 'e1',
    studentId: 'S001234',
    studentName: 'Aisha Patel',
    eventName: 'WIESOC Orientation Night',
    eventDate: '2026-03-05',
    hours: 3,
    category: 'Society Event',
    status: 'approved',
    evidenceFile: 'orientation_photo.jpg',
    evidenceType: 'image',
    submittedAt: '2026-03-06',
  },
  {
    id: 'e2',
    studentId: 'S001234',
    studentName: 'Aisha Patel',
    eventName: 'Industry Networking Dinner',
    eventDate: '2026-03-18',
    hours: 2,
    category: 'Networking',
    status: 'approved',
    evidenceFile: 'networking_event.jpg',
    evidenceType: 'image',
    submittedAt: '2026-03-19',
  },
  {
    id: 'e3',
    studentId: 'S001234',
    studentName: 'Aisha Patel',
    eventName: 'Monthly Committee Meeting',
    eventDate: '2026-04-02',
    hours: 1.5,
    category: 'Meeting',
    status: 'approved',
    evidenceFile: 'meeting_minutes.pdf',
    evidenceType: 'pdf',
    submittedAt: '2026-04-03',
  },
  {
    id: 'e4',
    studentId: 'S001234',
    studentName: 'Aisha Patel',
    eventName: 'Women in Tech Conference 2026',
    eventDate: '2026-04-20',
    hours: 6,
    category: 'Conference',
    status: 'approved',
    evidenceFile: 'conference_badge.jpg',
    evidenceType: 'image',
    submittedAt: '2026-04-21',
  },
  {
    id: 'e5',
    studentId: 'S001234',
    studentName: 'Aisha Patel',
    eventName: 'Robotics Workshop Volunteer',
    eventDate: '2026-05-10',
    hours: 4,
    category: 'Volunteering',
    status: 'approved',
    evidenceFile: 'workshop_volunteer.jpg',
    evidenceType: 'image',
    submittedAt: '2026-05-11',
  },
  {
    id: 'e6',
    studentId: 'S001234',
    studentName: 'Aisha Patel',
    eventName: 'Resume Workshop',
    eventDate: '2026-05-22',
    hours: 2,
    category: 'Workshop',
    status: 'approved',
    evidenceFile: 'workshop_cert.jpg',
    evidenceType: 'image',
    submittedAt: '2026-05-23',
  },
  {
    id: 'e7',
    studentId: 'S001234',
    studentName: 'Aisha Patel',
    eventName: 'Engineering Expo Help Desk',
    eventDate: '2026-06-08',
    hours: 5,
    category: 'Volunteering',
    status: 'approved',
    evidenceFile: 'expo_photo.jpg',
    evidenceType: 'image',
    submittedAt: '2026-06-09',
  },
  {
    id: 'e8',
    studentId: 'S001234',
    studentName: 'Aisha Patel',
    eventName: 'Mentor Coffee Chat',
    eventDate: '2026-06-25',
    hours: 1,
    category: 'Networking',
    status: 'rejected',
    evidenceFile: 'coffee_chat.jpg',
    evidenceType: 'image',
    rejectionReason: 'Evidence photo does not clearly show the event. Please resubmit with a clearer image or supplementary proof.',
    submittedAt: '2026-06-26',
  },
  {
    id: 'e9',
    studentId: 'S001234',
    studentName: 'Aisha Patel',
    eventName: 'July Committee Meeting',
    eventDate: '2026-07-09',
    hours: 1.5,
    category: 'Meeting',
    status: 'pending',
    evidenceFile: 'july_meeting.jpg',
    evidenceType: 'image',
    submittedAt: '2026-07-10',
  },
  {
    id: 'e10',
    studentId: 'S002345',
    studentName: 'Priya Sharma',
    eventName: 'WIESOC Orientation Night',
    eventDate: '2026-03-05',
    hours: 3,
    category: 'Society Event',
    status: 'pending',
    evidenceFile: 'orientation2.jpg',
    evidenceType: 'image',
    submittedAt: '2026-03-07',
  },
  {
    id: 'e11',
    studentId: 'S003456',
    studentName: 'Mei Lin',
    eventName: 'Industry Networking Dinner',
    eventDate: '2026-03-18',
    hours: 2,
    category: 'Networking',
    status: 'pending',
    evidenceFile: 'networking2.jpg',
    evidenceType: 'image',
    submittedAt: '2026-03-20',
  },
]
